cocognite/urls.py
import notifications.urls
from django.views.generic import TemplateView

from cocognite import settings
from dj_rest_auth.registration.views import VerifyEmailView
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path

from cocognite.settings import ENVIRONMENT
from src.accounts.views import GoogleLoginView, CustomRegisterAccountView
from django.views.static import serve

urlpatterns = [
    path('', include('src.website.urls', namespace='website')),
    path('404/', TemplateView.as_view(template_name='404.html'), name='404'),
    path('500/', TemplateView.as_view(template_name='500.html'), name='500'),
]

urlpatterns += [
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    path('', include('src.payments.urls', namespace='payment-stripe')),
    path('a/', include('src.portals.admins.urls', namespace='admin-portal')),
    path('c/', include('src.portals.customer.urls', namespace='moderator-portal')),
    path('api/', include('src.api.urls', namespace='api')),
    re_path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

urlpatterns += [
    path('auth/', include('dj_rest_auth.urls')),
    path('auth/registration/', CustomRegisterAccountView.as_view(), name='account_create_new_user'),
    path('auth/google/', GoogleLoginView.as_view(), name='google-login-view'),
    # re_path(r'^account-confirm-email/', VerifyEmailView.as_view(), name='account_email_verification_sent'),
    # re_path(r'^account-confirm-email/(?P<key>[-:\w]+)/$', VerifyEmailView.as_view(), name='account_confirm_email'),
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

src/accounts/urls.py
from django.urls import path
from .views import CrossAuthView, IdentificationCheckView, UserUpdateView, view_activate

app_name = "accounts"
urlpatterns = [
    path('cross-auth/', CrossAuthView.as_view(), name='cross-auth-view'),
    path('identification-check/', IdentificationCheckView.as_view(), name='identification-check'),
    path('user/change/', UserUpdateView.as_view(), name='user-change'),

    path('activate/<uidb64>/<token>/', view_activate, name='activate'),
]

src/website/urls.py
from django.urls import path
from .views import (
    HomeView, PrivacyPolicyView, TermsAndConditionsView,
    BlogDetailView, BlogView, ContactView, ComingSoonView, LoginView, SignUpView, ForgetPasswordView,
    SupportView, AboutUsView
)

app_name = "website"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('privacy-policy/', PrivacyPolicyView.as_view(), name='privacy-policy'),
    path('terms-and-conditions/', TermsAndConditionsView.as_view(), name='terms-and-conditions'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('forget/', ForgetPasswordView.as_view(), name='forget-password'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('support/', SupportView.as_view(), name='support'),
    path('about/', AboutUsView.as_view(), name='about'),
    path('blog/', BlogView.as_view(), name='blog'),
    path('blog/<slug:slug>/', BlogDetailView.as_view(), name='blog-detail'),
    path('coming-soon/', ComingSoonView.as_view(), name='coming-soon'),
]

src/website/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.utils.text import slugify
from django_resized import ResizedImageField

from src.accounts.models import User


class ArticleCategory(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "Article Category"
        verbose_name_plural = "Article Categories"

    def __str__(self):
        return self.name

    def get_articles(self):
        return Article.objects.filter(category__pk=self.pk)


class ArticleTag(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "Article Tag"
        verbose_name_plural = "Article Tags"

    def __str__(self):
        return self.name


class Article(models.Model):
    thumbnail = ResizedImageField(
        upload_to='exarth/images/articles/thumbnail/', null=True, blank=True, quality=100,
        crop=['middle', 'center'],
        size=[250, 250],
        help_text='Take your time and create thumbnail image for your blog '
                  'size must be 250*250 and available format are JPG, JPEG and PNG only.'
    )
    banner_image = ResizedImageField(
        upload_to='exarth/images/articles/banner/', null=True, blank=True, quality=75,
        size=[760, 1024],
        help_text='Banner image will be visible at the top of your article, '
                  'size must be 1024*760 and available format are JPG, JPEG and PNG only.'
    )
    title = models.CharField(
        max_length=255, null=False, blank=False, unique=True,
    )
    category = models.ForeignKey(ArticleCategory, on_delete=models.SET_NULL, null=True, blank=False)

    description = models.TextField(null=False, blank=False)
    detailed_description = RichTextField(null=False, blank=False)
    posted_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    slug = models.SlugField(unique=True, null=False, blank=True)
    keywords = models.ManyToManyField(ArticleTag)

    read_time = models.PositiveIntegerField(null=False, blank=False, default=0)
    likes = models.PositiveIntegerField(null=False, blank=False, default=0)
    views = models.PositiveIntegerField(null=False, blank=False, default=0)

    is_active = models.BooleanField(default=True, blank=False, null=False)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'

    def __str__(self):
        return f'{self.title}'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Article, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.thumbnail.delete(save=True)
        self.banner_image.delete(save=True)
        super(Article, self).delete(*args, **kwargs)

src/website/forms.py
import django_filters
from django.forms import TextInput

from src.website.models import Article


class ArticleFilter(django_filters.FilterSet):

    class Meta:
        model = Article
        fields = {
            'title': ['icontains']
        }

src/website/views.py
from django.core.paginator import Paginator
from django.views.generic import TemplateView, ListView, DetailView

from src.website.forms import ArticleFilter
from src.website.models import Article, ArticleTag, ArticleCategory


class HomeView(TemplateView):
    template_name = 'website/home.html'

    def get_context_data(self, **kwargs):
        return super(HomeView, self).get_context_data(**kwargs)


class PrivacyPolicyView(TemplateView):
    template_name = 'website/policy.html'


class TermsAndConditionsView(TemplateView):
    template_name = 'website/terms.html'


class ContactView(TemplateView):
    template_name = 'website/contact.html'


class SupportView(TemplateView):
    template_name = 'website/support.html'


class AboutUsView(TemplateView):
    template_name = 'website/about-us.html'


class Error404View(TemplateView):
    template_name = 'website/404.html'


class BlogView(TemplateView):
    template_name = 'website/blog.html'

    def get_context_data(self, **kwargs):
        context = super(BlogView, self).get_context_data(**kwargs)
        context['article_categories'] = ArticleCategory.objects.all()
        context['article_tags'] = ArticleTag.objects.all()
        context['article_recents'] = Article.objects.all()[:5]

        article_filter = ArticleFilter(self.request.GET, queryset=Article.objects.all())
        context['article_filter_form'] = article_filter.form

        paginator = Paginator(article_filter.qs, 50)
        page_number = self.request.GET.get('page')
        article_page_object = paginator.get_page(page_number)

        context['article_list'] = article_page_object

        return context


class BlogDetailView(DetailView):
    queryset = Article.objects.all()
    template_name = 'website/blog-details.html'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        context['article_categories'] = ArticleCategory.objects.all()
        context['article_tags'] = ArticleTag.objects.all()
        context['article_recents'] = Article.objects.all()[:5]
        return context


class ComingSoonView(TemplateView):
    template_name = 'website/coming-soon.html'


class LoginView(TemplateView):
    template_name = 'website/sign-in.html'


class SignUpView(TemplateView):
    template_name = 'website/sign-up.html'


class ForgetPasswordView(TemplateView):
    template_name = 'website/forgot.html'

src/website/templates/website/include/footer.html
{% load static %}

<div class="footer-section-03 bg-white-lilac footer-section-03--modifiar-01">
    <div class="container">
        <div class="row">
            <div class="col-xxl-4 col-lg-12 col-sm-6  col-xs-6">
                <div class="footer-section-03__wrapper">
                    <div class="logo">
                        <a href="#"><img src="{% static 'core/images/SKISIP WALLET.png' %}" alt="logo" height="200"></a>
                    </div>
                    <div class="text">
                        <p class=" text-dark">In the fast-paced world of modern technology,<br
                                class="d-none d-lg-block d-xxl-none">
                            many leadership executives and organizations understand that building.</p>
                    </div>
                    <div class="footer-section-03__wrapper--button-group">
                        <div class="text">
                            <h6>Get Our Mobile Apps From:</h6>
                        </div>
                        <div class="button-group">
                            <a class="btn btn-primary" href="#">
                                Apple Store
                                <svg width="18" height="18" viewBox="0 0 18 18" fill="none"
                                     xmlns="http://www.w3.org/2000/svg">
                                    <g clip-path="url(#clip0_0_3889)">
                                        <path d="M12.3745 0C11.4149 0.0663746 10.2932 0.680621 9.63963 1.48049C9.04338 2.20611 8.55289 3.28386 8.74414 4.33122C9.79263 4.36385 10.876 3.73498 11.5037 2.92161C12.091 2.16449 12.5353 1.09349 12.3745 0Z"
                                              fill=""/>
                                        <path d="M16.1667 6.039C15.2454 4.88363 13.9505 4.21313 12.7276 4.21313C11.1133 4.21313 10.4304 4.98601 9.30877 4.98601C8.15228 4.98601 7.27366 4.21538 5.87754 4.21538C4.50618 4.21538 3.04594 5.0535 2.12007 6.48675C0.81845 8.50498 1.0412 12.2996 3.15056 15.5317C3.90543 16.6882 4.91343 17.9887 6.23192 17.9999C7.40529 18.0112 7.73603 17.2473 9.32565 17.2394C10.9153 17.2304 11.2168 18.0101 12.3879 17.9977C13.7075 17.9876 14.7706 16.5464 15.5255 15.3899C16.0666 14.5608 16.268 14.1435 16.6876 13.2075C13.6355 12.0453 13.1461 7.70511 16.1667 6.039Z"
                                              fill=""/>
                                    </g>
                                    <defs>
                                        <clipPath id="clip0_0_3889">
                                            <rect width="18" height="18" fill="white"/>
                                        </clipPath>
                                    </defs>
                                </svg>
                            </a>
                            <a class="btn btn-primary" href="#">
                                Play Store
                                <svg width="18" height="18" viewBox="0 0 18 18" fill="none"
                                     xmlns="http://www.w3.org/2000/svg">
                                    <g clip-path="url(#clip0_0_3884)">
                                        <path d="M16.3131 7.71686L3.15286 0.194229C2.92597 0.0646286 2.67337 0 2.42077 0C2.41563 0 2.41057 0.000685714 2.40551 0.000685714C2.37157 0.00102857 2.33771 0.00274286 2.30394 0.0054C2.28868 0.0066 2.27351 0.00822857 2.25826 0.00994286C2.23186 0.0128571 2.20554 0.0165429 2.17931 0.0209143C2.1698 0.0225429 2.1602 0.0230571 2.15068 0.0248571L2.1512 0.0255429C1.98723 0.0558 1.8272 0.113571 1.67848 0.199886C1.223 0.464143 0.942627 0.950914 0.942627 1.47746V16.5226C0.942627 17.0492 1.223 17.5359 1.67848 17.8002C1.82711 17.8865 1.98714 17.9444 2.15111 17.9746L2.15068 17.9752C2.15926 17.9769 2.16791 17.9774 2.1764 17.9787C2.2046 17.9835 2.23288 17.9875 2.26126 17.9905C2.27548 17.992 2.28963 17.9936 2.30386 17.9947C2.3372 17.9973 2.37046 17.9989 2.40388 17.9993C2.40954 17.9994 2.41511 18.0001 2.42077 18.0001C2.67337 18.0001 2.92597 17.9355 3.15286 17.8059L16.3131 10.2831C16.7732 10.0201 17.0572 9.53083 17.0572 9.00069C17.0572 9.00069 17.0572 9.00043 17.0572 9.00034C17.0572 9.00034 17.0572 9.00008 17.0572 9C17.0572 9 17.0572 8.99974 17.0572 8.99966C17.0572 8.99966 17.0572 8.9994 17.0572 8.99931C17.0572 8.46926 16.7732 7.98 16.3131 7.71686ZM11.1087 6.22294L9.80017 7.93954L6.47103 3.57189L11.1087 6.22294ZM15.675 9.16689L6.47103 14.4281L12.2339 6.8676L15.6749 8.83449C15.7345 8.86851 15.7715 8.93229 15.7715 9.0006C15.7715 9.06917 15.7344 9.13294 15.675 9.16689Z"
                                              fill=""/>
                                    </g>
                                    <defs>
                                        <clipPath id="clip0_0_3884">
                                            <rect width="18" height="18" fill="white"/>
                                        </clipPath>
                                    </defs>
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xxl-2 col-lg-4 col-md-6 col-xs-6 col-sm-6">
                <div class="footer-section-03__widget widget-01">
                    <h6 class="title">Company</h6>
                    <ul class="list-group list-unstyled">
                        <li><a href="{% url 'website:terms-and-conditions' %}">Terms</a></li>
                        <li><a href="{% url 'website:privacy-policy' %}">Privacy Policy</a></li>
                        <li><a href="{% url 'website:blog' %}">Blog</a></li>
                        <li><a href="{% url 'website:contact' %}">Contact Us</a></li>
                        <li><a href="{% url 'website:about' %}">About Us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-xxl-3 col-lg-4 col-sm-6 col-xs-6">
                <div class="footer-section-03__widget widget-02">
                    <h6 class="title">Get Help</h6>
                    <ul class="list-group list-unstyled">
                        <li><a href="{% url 'website:support' %}">Video Tutorials</a></li>
                        <li><a href="{% url 'website:support' %}">Faq Questions</a></li>
                        <li><a href="{% url 'website:support' %}">Documentations</a></li>
                        <li><a href="{% url 'website:signup' %}">Register</a></li>
                        <li><a href="{% url 'website:login' %}">Login</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-xxl-3 col-lg-4 col-sm-6 order-lg-4 col-xs-6">
                <div class="footer-section-03__newsletter">
                    <h6>Newsletter</h6>
                    <p>Sign up and receive the latest tips via email.</p>
                    <div class="footer-section-03__newsletter--form">
                        <form action="#">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Enter your mail address">
                                <div class="icon">
                                    <img src="{% static 'website/image/l-2/mail.png' %}" alt="mail">
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary w-100">
                                Subscribe Now
                                <svg width="18" height="18" viewBox="0 0 18 18" fill="none"
                                     xmlns="http://www.w3.org/2000/svg">
                                    <g clip-path="url(#clip0_0_3856)">
                                        <path d="M6.56226 13.209V16.6875C6.56226 16.9305 6.71826 17.1457 6.94925 17.2222C7.007 17.241 7.06625 17.25 7.12475 17.25C7.30025 17.25 7.46975 17.1675 7.57775 17.0205L9.6125 14.2515L6.56226 13.209Z"
                                              fill="white"/>
                                        <path d="M17.7633 0.10334C17.5908 -0.0189101 17.3643 -0.0354101 17.1768 0.0628399L0.301795 8.87534C0.102295 8.97959 -0.0154549 9.19259 0.00104508 9.41684C0.0182951 9.64184 0.167545 9.83384 0.379795 9.90659L5.07105 11.5101L15.0618 2.96759L7.3308 12.2818L15.193 14.9691C15.2515 14.9886 15.313 14.9991 15.3745 14.9991C15.4765 14.9991 15.5778 14.9713 15.667 14.9173C15.8095 14.8303 15.9063 14.6841 15.931 14.5198L17.9935 0.64484C18.0243 0.43484 17.9358 0.22634 17.7633 0.10334Z"
                                              fill="white"/>
                                    </g>
                                    <defs>
                                        <clipPath id="clip0_0_3856">
                                            <rect width="18" height="18" fill="white"/>
                                        </clipPath>
                                    </defs>
                                </svg>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="copyright-block copyright-block--modifi-02">
    <div class="container">
        <div class="row">
            <div class="copyright-block__wrapper">
                <ul class="list-unstyled copyright-block__social">
                    <li class="list-item"><a href="https://www.facebook.com/"><i class="fab fa-facebook-f"></i></a></li>
                    <li class="list-item"><a href="https://dribbble.com/"><i class="fab fa-dribbble"></i></a></li>
                    <li class="list-item"><a href="https://github.com/"><i class="fab fa-github"></i></a></li>
                    <li class="list-item"><a href="https://twitter.com/"><i class="fab fa-twitter"></i></a></li>
                </ul>
                <div class="copyright-block__content">
                    <p class="text-dark">© 2022 Name. Designed and Developed by
                        <a target="_blank" href="https://exarth.com/">Exarth</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

src/website/templates/website/include/header.html
{% load static %}

<header class="site-header site-header--menu-center logo-dark mobile-menu-trigger-dark">
    <div class="container">
        <nav class="navbar site-navbar">
            <!-- Brand Logo-->
            <div class="site-header__brand">
                <a href="/">
                    <!-- light version logo (logo must be black)-->
                    <img src="{% static 'core/images/logo-50.png' %}" alt="logo" class="logo-white-black">
                    <!-- light version logo (logo must be black)-->
                    <img src="{% static 'core/images/logo-50.png' %}" alt="logo" class="logo-white">
                    <!-- Dark version logo (logo must be White)-->
                    <img src="{% static 'core/images/logo-50.png' %}" alt="logo" class="logo-black">
                </a>
            </div>
            <div class="menu-block-wrapper ">
                <div class="menu-overlay"></div>
                <nav class="menu-block menu-block-inner" id="append-menu-header">
                    <div class="mobile-menu-head">
                        <div class="go-back">
                            <i class="fa fa-angle-left"></i>
                        </div>
                        <div class="current-menu-title"></div>
                        <div class="mobile-menu-close">&times;</div>
                    </div>
                    <ul class="site-menu-main">
                        <li class="nav-item nav-item-has-children">
                            <a href="{% url 'website:home' %}" class="nav-link-item drop-trigger">Home
                            </a>
                        </li>
                        <li class="nav-item nav-item-has-children">
                            <a href="{% url 'website:about' %}" class="nav-link-item drop-trigger">About
                            </a>
                        </li>
                        <li class="nav-item nav-item-has-children">
                            <a href="{% url 'website:contact' %}" class="nav-link-item drop-trigger">Contact
                            </a>
                        </li>
                        <li class="nav-item nav-item-has-children">
                            <a href="{% url 'website:blog' %}" class="nav-link-item drop-trigger">Blog
                            </a>
                        </li>
                        <li class="nav-item nav-item-has-children">
                            <a href="{% url 'website:support' %}" class="nav-link-item drop-trigger">Support
                            </a>
                        </li>
                    </ul>
                </nav>
                <div class="header-button header-btn site-header__btns--01">
                    {% if request.user.is_authenticated %}
                        <a class="btn btn-primary" href="{% url 'accounts:cross-auth-view' %}">
                            Dashboard <img src='{% static 'website/image/svg/arrow.svg' %}' class='make-it-inline'
                                       alt='arrow'>
                        </a>
                    {% else %}
                        <a class="btn btn-primary" href="{% url 'account_login' %}">
                            Login <img src='{% static 'website/image/svg/arrow.svg' %}' class='make-it-inline'
                                       alt='arrow'>
                        </a>
                    {% endif %}
                </div>
            </div>
            <!-- mobile menu trigger -->
            <div class="mobile-menu-trigger">
                <span></span>
            </div>
            <!--/.Mobile Menu Hamburger Ends-->
        </nav>
    </div>
</header>