cocognite/urls.py
import notifications.urls
from django.views.generic import TemplateView

from cocognite import settings
from dj_rest_auth.registration.views import VerifyEmailView
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path

from cocognite.settings import ENVIRONMENT
from src.accounts.views import GoogleLoginView, CustomRegisterAccountView
from django.views.static import serve

urlpatterns = [
    path('', include('src.website.urls', namespace='website')),
    path('404/', TemplateView.as_view(template_name='404.html'), name='404'),
    path('500/', TemplateView.as_view(template_name='500.html'), name='500'),
]

urlpatterns += [
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    path('', include('src.payments.urls', namespace='payment-stripe')),
    path('a/', include('src.portals.admins.urls', namespace='admin-portal')),
    path('c/', include('src.portals.customer.urls', namespace='moderator-portal')),
    path('api/', include('src.api.urls', namespace='api')),
    re_path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

urlpatterns += [
    path('auth/', include('dj_rest_auth.urls')),
    path('auth/registration/', CustomRegisterAccountView.as_view(), name='account_create_new_user'),
    path('auth/google/', GoogleLoginView.as_view(), name='google-login-view'),
    # re_path(r'^account-confirm-email/', VerifyEmailView.as_view(), name='account_email_verification_sent'),
    # re_path(r'^account-confirm-email/(?P<key>[-:\w]+)/$', VerifyEmailView.as_view(), name='account_confirm_email'),
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

src/website/urls.py
from django.urls import path
from .views import (
    HomeView, PrivacyPolicyView, TermsAndConditionsView,
    BlogDetailView, BlogView, ContactView, ComingSoonView, LoginView, SignUpView, ForgetPasswordView,
    SupportView, AboutUsView
)

app_name = "website"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('privacy-policy/', PrivacyPolicyView.as_view(), name='privacy-policy'),
    path('terms-and-conditions/', TermsAndConditionsView.as_view(), name='terms-and-conditions'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('forget/', ForgetPasswordView.as_view(), name='forget-password'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('support/', SupportView.as_view(), name='support'),
    path('about/', AboutUsView.as_view(), name='about'),
    path('blog/', BlogView.as_view(), name='blog'),
    path('blog/<slug:slug>/', BlogDetailView.as_view(), name='blog-detail'),
    path('coming-soon/', ComingSoonView.as_view(), name='coming-soon'),
]

src/website/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.utils.text import slugify
from django_resized import ResizedImageField

from src.accounts.models import User


class ArticleCategory(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "Article Category"
        verbose_name_plural = "Article Categories"

    def __str__(self):
        return self.name

    def get_articles(self):
        return Article.objects.filter(category__pk=self.pk)


class ArticleTag(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "Article Tag"
        verbose_name_plural = "Article Tags"

    def __str__(self):
        return self.name


class Article(models.Model):
    thumbnail = ResizedImageField(
        upload_to='exarth/images/articles/thumbnail/', null=True, blank=True, quality=100,
        crop=['middle', 'center'],
        size=[250, 250],
        help_text='Take your time and create thumbnail image for your blog '
                  'size must be 250*250 and available format are JPG, JPEG and PNG only.'
    )
    banner_image = ResizedImageField(
        upload_to='exarth/images/articles/banner/', null=True, blank=True, quality=75,
        size=[760, 1024],
        help_text='Banner image will be visible at the top of your article, '
                  'size must be 1024*760 and available format are JPG, JPEG and PNG only.'
    )
    title = models.CharField(
        max_length=255, null=False, blank=False, unique=True,
    )
    category = models.ForeignKey(ArticleCategory, on_delete=models.SET_NULL, null=True, blank=False)

    description = models.TextField(null=False, blank=False)
    detailed_description = RichTextField(null=False, blank=False)
    posted_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    slug = models.SlugField(unique=True, null=False, blank=True)
    keywords = models.ManyToManyField(ArticleTag)

    read_time = models.PositiveIntegerField(null=False, blank=False, default=0)
    likes = models.PositiveIntegerField(null=False, blank=False, default=0)
    views = models.PositiveIntegerField(null=False, blank=False, default=0)

    is_active = models.BooleanField(default=True, blank=False, null=False)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'

    def __str__(self):
        return f'{self.title}'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Article, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.thumbnail.delete(save=True)
        self.banner_image.delete(save=True)
        super(Article, self).delete(*args, **kwargs)

src/website/forms.py
import django_filters
from django.forms import TextInput

from src.website.models import Article


class ArticleFilter(django_filters.FilterSet):

    class Meta:
        model = Article
        fields = {
            'title': ['icontains']
        }

src/website/views.py
from django.core.paginator import Paginator
from django.views.generic import TemplateView, ListView, DetailView

from src.website.forms import ArticleFilter
from src.website.models import Article, ArticleTag, ArticleCategory


class HomeView(TemplateView):
    template_name = 'website/home.html'

    def get_context_data(self, **kwargs):
        return super(HomeView, self).get_context_data(**kwargs)


class PrivacyPolicyView(TemplateView):
    template_name = 'website/policy.html'


class TermsAndConditionsView(TemplateView):
    template_name = 'website/terms.html'


class ContactView(TemplateView):
    template_name = 'website/contact.html'


class SupportView(TemplateView):
    template_name = 'website/support.html'


class AboutUsView(TemplateView):
    template_name = 'website/about-us.html'


class Error404View(TemplateView):
    template_name = 'website/404.html'


class BlogView(TemplateView):
    template_name = 'website/blog.html'

    def get_context_data(self, **kwargs):
        context = super(BlogView, self).get_context_data(**kwargs)
        context['article_categories'] = ArticleCategory.objects.all()
        context['article_tags'] = ArticleTag.objects.all()
        context['article_recents'] = Article.objects.all()[:5]

        article_filter = ArticleFilter(self.request.GET, queryset=Article.objects.all())
        context['article_filter_form'] = article_filter.form

        paginator = Paginator(article_filter.qs, 50)
        page_number = self.request.GET.get('page')
        article_page_object = paginator.get_page(page_number)

        context['article_list'] = article_page_object

        return context


class BlogDetailView(DetailView):
    queryset = Article.objects.all()
    template_name = 'website/blog-details.html'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        context['article_categories'] = ArticleCategory.objects.all()
        context['article_tags'] = ArticleTag.objects.all()
        context['article_recents'] = Article.objects.all()[:5]
        return context


class ComingSoonView(TemplateView):
    template_name = 'website/coming-soon.html'


class LoginView(TemplateView):
    template_name = 'website/sign-in.html'


class SignUpView(TemplateView):
    template_name = 'website/sign-up.html'


class ForgetPasswordView(TemplateView):
    template_name = 'website/forgot.html'

src/website/templates/website/base.html
{% load static %}
<!doctype html>

<html lang="zxx">
<head>

    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <link rel="icon" href="{% static "core/images/logo-50.png" %}">

    <title>
        {% block title %}
            SkiSip Wallet |
            {% block sub_title %}
                Home
            {% endblock %}
        {% endblock %}
    </title>

    <link rel="stylesheet" href="{% static 'website/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'website/fonts/typography-font/typo.css' %}"/>
    <link rel="stylesheet" href="{% static 'website/fonts/fontawesome-5/css/all.css' %}"/>

    <link rel="stylesheet" href="{% static 'website/plugins/aos/aos.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/plugins/fancybox/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/plugins/nice-select/nice-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/plugins/slick/slick.min.css' %}">

    <link rel="stylesheet" href="{% static 'website/css/main.css' %}"/>

    {% block css_links %}
    {% endblock %}

</head>
<body>

<div class="preloader-wrapper" id="loader">
    <svg class="spinner" width="65px" height="65px" viewBox="0 0 66 66" xmlns="http://www.w3.org/2000/svg">
        <circle class="path" fill="none" stroke-width="6" stroke-linecap="round" cx="33" cy="33" r="30"></circle>
    </svg>
</div>
<div class="site-wrapper overflow-hidden">

    {% block header %}
        {% include 'website/include/header.html' %}
    {% endblock %}

    {% block content %}

    {% endblock %}

    {% block footer %}
        {% include 'website/include/footer.html' %}
    {% endblock %}
</div>

<script src="{% static 'website/js/vendor.min.js' %}"></script>
<script src="{% static 'website/plugins/fancybox/jquery.fancybox.min.js' %}"></script>
<script src="{% static 'website/plugins/nice-select/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'website/plugins/aos/aos.min.js' %}"></script>
<script src="{% static 'website/plugins/counter-up/jquery.counterup.min.js' %}"></script>
<script src="{% static 'website/plugins/counter-up/waypoints.min.js' %}"></script>
<script src="{% static 'website/plugins/slick/slick.min.js' %}"></script>
<script src="{% static 'website/plugins/skill-bar/skill.bars.jquery.html' %} "></script>
<script src="{% static 'website/plugins/isotope/isotope.pkgd.min.js' %}"></script>

<script src="{% static 'website/js/custom.js' %}"></script>
<script src="{% static 'website/js/slider-activations.js' %}"></script>
<script src="{% static 'website/js/menu.js' %}"></script>

{% block internal_js %}

{% endblock %}


</body>
</html>

{% block external_js %}{% endblock %}

src/website/templates/website/blog-details.html
{% extends 'website/base.html' %}
{% load static %}

{% block sub_title %}
    {{ object.title }}
{% endblock %}

{% block content %}

    <div class="breadcrumb bg-white-lilac ">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-6 col-lg-8 col-xs-10">
                    <div class="page-title-block-two breadcrumb__content text-center">
                        <h1 class="title">{{ object.title }}</h1>
                        <p class="text-dark">{{ object.description }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="breadcrumb__navigation">
            <p class="breadcrumb__navigation--text"><a class="d-block heading-dark" href="{% url 'website:blog' %}">Blog</a><span
                    class="dot"></span><span class="page-text">Blog Details</span></p>
        </div>
    </div>

    <div class="blog-details-area">
        <div class="container">
            <div class="blog-details-area__wrapper">
                <div class="row justify-content-center">
                    <div class="col-lg-4 col-md-8 col-xs-10 order-lg-2">
                        <div class="blog-content-area__categories">
                            <div class="categories-block">
                                <h6 class="content-title heading-dark">Categories</h6>

                                {% if article_categories %}
                                    <ul>
                                        {% for article_category in article_categories %}

                                            <li>
                                                <a href="#"><span class="text">{{ article_category.name }}</span></a>
                                            </li>

                                        {% endfor %}
                                    </ul>
                                {% else %}
                                    <p class="text-danger mt-4">
                                        <b><i class="fa fa-exclamation-circle"></i> Tags are not defined yet.</b>
                                    </p>
                                {% endif %}


                            </div>
                        </div>
                        <div class="blog-content-area__tags">
                            <div class="tags-block">
                                <h6 class="content-title heading-dark">Tags</h6>

                                {% if article_tags %}
                                    <ul>
                                        {% for article_tag in article_tags %}

                                            <li>
                                                <a href="#">
                                                    {{ article_tag.name }}
                                                </a>
                                            </li>

                                        {% endfor %}
                                    </ul>
                                {% else %}
                                    <p class="text-danger mt-2">
                                        <b><i class="fa fa-exclamation-circle"></i> Categories are not defined yet.</b>
                                    </p>
                                {% endif %}

                            </div>
                        </div>
                    </div>
                    <div class="col-lg-8 order-lg-1">
                        <div class="blog-details-area__content">
                            <div class="blog-details-area__content--card">
                                <div class="blog-details-card">
                                    {% if article_recent.banner_image %}
                                        <img src="{{ article_recent.banner_image.url }}" class="w-100"
                                             alt="card">
                                    {% else %}
                                        <img src="{% static 'core/images/noimage.jpg' %}" class="w-100"
                                             alt="card">
                                    {% endif %}
                                    <div class="card-img">
                                    </div>
                                    <div class="card-body">
                                        <div class="meta">
                                            <div class="meta__date">
                                                <span class="date text-dark"><img
                                                        src="{% static 'website/image/svg/calendar.svg' %}"> {{ object.created_on }} </span>
                                            </div>
                                            <div class="meta__time">
                                            <span class="time text-dark"><img
                                                    src="{% static 'website/image/svg/clock.svg' %}"> {{ object.read_time }} min read </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="blog-details-area__content--quote">
                                {{ object.detailed_description|safe }}
                            </div>
                            <div class="blog-details-area__content--group">
                                <div class="popular-tags">
                                    <h6>Popular Tags:</h6>
                                    <ul>
                                        {% for tag in object.keywords.all %}
                                            <li><a href="#">{{ tag.name }}</a></li>
                                        {% endfor %}

                                    </ul>
                                </div>
                                <div class="share-block">
                                    <h6>Share With:</h6>
                                    <ul>
                                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                        <li><a href="#"><i class="fab fa-dribbble"></i></a></li>
                                        <li><a href="#"><i class="fab fa-github"></i></a></li>
                                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="blog-section-02">
        <div class="container">
            <div class="row align-items-center justify-content-center blog-section-02__content">
                <div class="col-sm-6">
                    <div class="section-content-block text-center text-sm-start">
                        <h6 class="subtitle text-primary mb-10">Blog & News</h6>
                        <h2 class="title">Our Latest Blog & News</h2>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="section-button text-center mt-4 mt-sm-0 text-sm-end">
                        <a class="btn btn-1 btn-primary" href="blog.html">
                            Read Our Blogs
                            <svg width="8" height="14" viewBox="0 0 8 14" fill="none"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path d="M1 13L7 7L1 1" stroke="" stroke-width="2" stroke-linecap="round"
                                      stroke-linejoin="round"/>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
            <div class="row card-row justify-content-center">

                {% if article_recents %}
                    {% for article_recent in article_recents %}

                        <div class="col-md-6 col-xl-4" data-aos="fade-up" data-aos-delay="150" data-aos-duration="800">
                            <a href="{% url 'website:blog-detail' article_recent.slug %}" class="d-block">
                                <div class="card-blog card-blog--02">
                                    <div class="card-image">

                                        {% if article_recent.banner_image %}
                                            <img src="{{ article_recent.banner_image.url }}" class="w-100"
                                                 alt="card">
                                        {% else %}
                                            <img src="{% static 'core/images/no_content.png' %}" class="w-100"
                                                 alt="card">
                                        {% endif %}

                                        <div class="meta">
                                            <span class="text-dark">{{ article_recent.created_on }}</span>
                                        </div>
                                    </div>
                                    <div class="card-body">
                                        <h6 class="titel">{{ article_recent.title }}</h6>
                                        <p class="text-dark">{{ article_recent.description }}</p>
                                        <div class="author-block">
                                            <div class="d-flex align-items-center">
                                                <div class="author">
                                                    <img src="{% static 'core/images/no-user.png' %}"
                                                         alt="author">
                                                </div>
                                                <div class="author-name">
                                                    <h6 class="heading-dark">{{ article_recent.posted_by.username }}</h6>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>

                    {% endfor %}
                {% endif %}

            </div>
        </div>
    </div>

{% endblock %}

src/website/templates/website/forgot.html
{% extends 'website/base.html' %}
{% load static %}


{% block sub_title %}
    Forget Password
{% endblock %}

{% block header %}

{% endblock %}


{% block content %}

    <div class="forgot-content">
        <div class="forgot-content__bg">
            <img src="{% static 'website/image/innerpage/forgot.png' %}" alt="signup">
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-6">
                    <div class="account-form">
                        <div class="section-content-block">
                            <h2 class="mb-10 title">Reset Password</h2>
                            <p class=" text-dark">Enter your email to get reset link.
                            </p>
                        </div>
                        <form action="#" class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <input type="email" class="form-control" placeholder="E-mail address">
                                    <div class="icon">
                                        <img src="{% static 'website/image/svg/mail.svg' %}" alt="mail"
                                             class="make-it-inline">
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-button">
                                    <button type="submit" class=" btn btn-primary w-100">Reset Password</button>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-texts form-texts-two">
                                    <p class="heading-dark">Remember the password?
                                        <a class=" text-primary" href="{% url 'website:login' %}">Sign in</a>
                                    </p>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block footer %}

{% endblock %}

src/website/templates/website/sign-up.html
{% extends 'website/base.html' %}
{% load static %}


{% block sub_title %}
    Sign Up
{% endblock %}

{% block header %}

{% endblock %}k


{% block content %}

    <div class="signup-content">
        <div class="signup-content__bg">
            <img src="{% static 'website/image/innerpage/signup.png' %}" alt="signup">
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="account-form">
                        <div class="section-content-block">
                            <h2 class="mb-10 title">Create An Account</h2>
                            <p class=" text-dark">Create an account today and grow your business with Bestkit</p>
                        </div>
                        <form action="#" class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Full Name">
                                    <div class="icon">
                                        <img src="{% static 'website/image/svg/user.svg' %}" alt="user" class="make-it-inline">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="email" class="form-control" placeholder="E-mail address">
                                    <div class="icon">
                                        <img src="{% static 'website/image/svg/mail.svg' %}" alt="mail" class="make-it-inline">
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group mb-0">
                                    <input type="password" class="form-control" placeholder="Password">
                                    <div class="icon">
                                        <img src="{% static 'website/image/svg/lock.svg' %}" alt="lock" class="make-it-inline">
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" id="gridCheck">
                                    <label class="form-check-label" for="gridCheck">
                                        I have read and agree to the Terms & Conditions.
                                    </label>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-button">
                                    <button type="submit" class=" btn btn-primary w-100">Create Account</button>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-texts form-texts-one">
                                    <p class="text-dark">or</p>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-button mb-15">
                                    <a href="#" class=" btn-2 btn bg-white-lilac w-100">
                                        <img src="{% static 'website/image/svg/google.png' %}" alt="google" class="mr-15 mw-100"> Sign Up with
                                        Google</a>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-button">
                                    <a href="#" class=" btn btn-2 bg-white-lilac w-100">
                                        <img src="{% static 'website/image/svg/facebook.png' %}" alt="facebook" class="mr-15 mw-100"> Sign Up
                                        with Facebook</a>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-texts form-texts-two">
                                    <p class="heading-dark">
                                        Already have an account?
                                        <a class=" text-primary" href="{% url 'website:login' %}">Sign in</a>
                                    </p>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block footer %}

{% endblock %}