cocognite/urls.py
import notifications.urls
from django.views.generic import TemplateView

from cocognite import settings
from dj_rest_auth.registration.views import VerifyEmailView
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path

from cocognite.settings import ENVIRONMENT
from src.accounts.views import GoogleLoginView, CustomRegisterAccountView
from django.views.static import serve

urlpatterns = [
    path('', include('src.website.urls', namespace='website')),
    path('404/', TemplateView.as_view(template_name='404.html'), name='404'),
    path('500/', TemplateView.as_view(template_name='500.html'), name='500'),
]

urlpatterns += [
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    path('', include('src.payments.urls', namespace='payment-stripe')),
    path('a/', include('src.portals.admins.urls', namespace='admin-portal')),
    path('c/', include('src.portals.customer.urls', namespace='moderator-portal')),
    path('api/', include('src.api.urls', namespace='api')),
    re_path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

urlpatterns += [
    path('auth/', include('dj_rest_auth.urls')),
    path('auth/registration/', CustomRegisterAccountView.as_view(), name='account_create_new_user'),
    path('auth/google/', GoogleLoginView.as_view(), name='google-login-view'),
    # re_path(r'^account-confirm-email/', VerifyEmailView.as_view(), name='account_email_verification_sent'),
    # re_path(r'^account-confirm-email/(?P<key>[-:\w]+)/$', VerifyEmailView.as_view(), name='account_confirm_email'),
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

src/portals/admins/urls.py
from django.urls import path

from src.portals.admins.views import (
    DashboardView,
    UserListView, UserDetailView, UserUpdateView, UserPasswordResetView,
    TopUpListView, TopUpDetailView, TopUpInvoiceView,
    TransactionListView, TransactionDetailView, TransactionInvoiceView,
    WithdrawalListView, WithdrawalDetailView, WithdrawalInvoiceView,
    TicketListView, TicketDetailView,
    TicketStatusChangeView)

app_name = "admin-portal"
urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('user/', UserListView.as_view(), name='user-list'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/<int:pk>/change/', UserUpdateView.as_view(), name='user-update'),
    path('user/<int:pk>/password/reset/', UserPasswordResetView.as_view(), name='user-password-reset-view'),

    path('topup/', TopUpListView.as_view(), name='topup-list'),
    path('topup/<int:pk>/', TopUpDetailView.as_view(), name='topup-detail'),
    path('topup/<int:pk>/invoice/', TopUpInvoiceView.as_view(), name='topup-invoice'),

    path('transaction/', TransactionListView.as_view(), name='transaction-list'),
    path('transaction/<int:pk>/', TransactionDetailView.as_view(), name='transaction-detail'),
    path('transaction/<int:pk>/invoice/', TransactionInvoiceView.as_view(), name='transaction-invoice'),

    path('withdrawal/', WithdrawalListView.as_view(), name='withdrawal-list'),
    path('withdrawal/<int:pk>/', WithdrawalDetailView.as_view(), name='withdrawal-detail'),
    path('withdrawal/<int:pk>/invoice/', WithdrawalInvoiceView.as_view(), name='withdrawal-invoice'),

    path('ticket/', TicketListView.as_view(), name='ticket-list'),
    path('ticket/<int:pk>/', TicketDetailView.as_view(), name='ticket-detail'),
    path('ticket/<int:pk>/status/change/', TicketStatusChangeView.as_view(), name='ticket-status-change'),

]

src/portals/customer/urls.py
from django.urls import path
from .views import (
    DashboardView, WalletDetailView, WalletGenerateQRCodeView,
    TopUpListView, TopUpInvoiceView, TopUpDetailView, TopUpCreateView,
    TransactionListView, TransactionDetailView, TransactionInvoiceView, TransactionCreateView,
    WithdrawalListView, WithdrawalInvoiceView, WithdrawalDetailView, WithdrawalCreateView,
    UserSanctionsUpdateView,
    TicketListView, TicketCreateView, TicketDetailView,
    TransferFunds)

app_name = "customer-portal"
urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('wallet/', WalletDetailView.as_view(), name='wallet-detail'),
    path('wallet/<int:pk>/generate/qr-code/', WalletGenerateQRCodeView.as_view(), name='generate-qr-code'),
    path('user/sanctions/change/', UserSanctionsUpdateView.as_view(), name='user-sanctions-change'),

    path('topup/', TopUpListView.as_view(), name='topup-list'),
    path('topup/add/', TopUpCreateView.as_view(), name='topup-create'),
    path('topup/<int:pk>/', TopUpDetailView.as_view(), name='topup-detail'),
    path('topup/<int:pk>/invoice/', TopUpInvoiceView.as_view(), name='topup-invoice'),

    path('transaction/', TransactionListView.as_view(), name='transaction-list'),
    path('transaction/add/', TransactionCreateView.as_view(), name='transaction-create'),
    path('transaction/<int:pk>/', TransactionDetailView.as_view(), name='transaction-detail'),
    path('transaction/<int:pk>/invoice/', TransactionInvoiceView.as_view(), name='transaction-invoice'),

    path('withdrawal/', WithdrawalListView.as_view(), name='withdrawal-list'),
    path('withdrawal/add/', WithdrawalCreateView.as_view(), name='withdrawal-create'),
    path('withdrawal/<int:pk>/', WithdrawalDetailView.as_view(), name='withdrawal-detail'),
    path('withdrawal/<int:pk>/invoice/', WithdrawalInvoiceView.as_view(), name='withdrawal-invoice'),

    path('ticket/', TicketListView.as_view(), name='ticket-list'),
    path('ticket/add/', TicketCreateView.as_view(), name='ticket-create'),
    path('ticket/<int:pk>/', TicketDetailView.as_view(), name='ticket-detail'),

    path('transfers/', TransferFunds.as_view(), name='transfer')
]

src/portals/admins/models.py
from django.db import models
from django_resized import ResizedImageField
from src.accounts.models import Wallet


""" GENERAL """


class Country(models.Model):

    name = models.CharField(max_length=255, unique=True)
    short_code = models.CharField(max_length=2, unique=True)
    phone_code = models.CharField(max_length=5, unique=True)
    description = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Countries'

    def __str__(self):
        return self.name


""" MAIN """


class PaymentMethod(models.Model):
    name = models.CharField(max_length=255)
    icon = models.CharField(max_length=100, default="bx bx-transfer")
    image = ResizedImageField(
        upload_to='accounts/images/profiles/', null=True, blank=True, size=[100, 100], quality=75, force_format='PNG',
        help_text='size of image must be 100*100 and format must be png image file', crop=['middle', 'center']
    )
    description = models.TextField(null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = "Payment Methods"

    def __str__(self):
        return self.name


class TopUp(models.Model):
    STATUS_CHOICE = (
        ('com', 'Completed'),
        ('pen', 'Pending'),
        ('can', 'Cancelled'),
    )
    PAYMENT_METHOD_CHOICE = (
        ('str', 'Stripe'),
    )

    total = models.PositiveIntegerField()
    tax = models.PositiveIntegerField()
    received = models.PositiveIntegerField()
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE, blank=True)
    stripe_payment_intent = models.CharField(max_length=20000)
    status = models.CharField(choices=STATUS_CHOICE, max_length=3, default='pen')
    payment_method = models.CharField(choices=PAYMENT_METHOD_CHOICE, max_length=3, default='str')

    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']
        verbose_name_plural = "Top Ups"

    def __str__(self):
        return str(self.pk)


class Withdrawal(models.Model):
    STATUS_CHOICE = (
        ('com', 'Completed'),
        ('pen', 'Pending'),
        ('can', 'Cancelled'),
    )

    total = models.FloatField(verbose_name='Amount')
    tax = models.FloatField(default=0)
    received = models.FloatField(default=0)
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE, blank=True)
    connected_account = models.ForeignKey(
        'payments.ExternalAccount', on_delete=models.SET_NULL, null=True, blank=True
    )
    status = models.CharField(choices=STATUS_CHOICE, max_length=3)

    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']
        verbose_name_plural = "Withdrawals"

    def __str__(self):
        return str(self.pk)


class Transaction(models.Model):
    STATUS_CHOICE = (
        ('com', 'Completed'),
        ('pen', 'Pending'),
        ('can', 'Cancelled'),
    )
    TYPE_CHOICE = (
        ('p2p', 'Peer To Peer'),
    )

    total = models.PositiveIntegerField(default=0)
    tax = models.PositiveIntegerField(default=0)
    received = models.PositiveIntegerField(default=0)
    sender_wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE, blank=True, related_name='sender+')
    receiver_wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE, blank=True, related_name='receiver+')
    type = models.CharField(choices=TYPE_CHOICE, max_length=3, default='p2p')
    status = models.CharField(choices=STATUS_CHOICE, max_length=3, default='pen')

    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']
        verbose_name_plural = "Transactions"

    def __str__(self):
        return str(self.pk)


""" TICKET SYSTEM """


class TicketType(models.Model):
    PRIORITY_CHOICES = (
        ('h', 'High'),
        ('m', 'Medium'),
        ('l', 'Low'),
    )
    name = models.CharField(max_length=255)
    priority = models.CharField(max_length=1, choices=PRIORITY_CHOICES, default='m')

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.name


class Ticket(models.Model):
    PRIORITY_CHOICES = (
        ('h', 'High'),
        ('m', 'Medium'),
        ('l', 'Low'),
    )
    ticket_type = models.ForeignKey(TicketType, on_delete=models.CASCADE)
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)

    is_completed = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return str(self.pk)

src/portals/admins/templates/admins/topup_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Top up {% endblock %}

{% block page_heading %}
    {% if object.status == 'com' %}
        <b class="p-2 bg-success text-white"><i class="fa fa-check-circle"></i> {{ object.get_status_display }}</b>
    {% elif object.status == 'pen' %}
        <b class="p-2 bg-warning text-white"><i class="fa fa-exclamation-triangle"></i> {{ object.get_status_display }}</b>
    {% else %}
        <b class="p-2 bg-danger text-white"><i class="fa fa-times-circle"></i> {{ object.get_status_display }}</b>
    {% endif %}
    <b class="p-2 bg-dark text-white"><i class="bx bx-transfer"></i> {{ object.get_payment_method_display }}</b>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-8">

            <div class="card-body border-bottom">
                <p class="my-0 card-title">Top Up Information</p>
            </div>
            <div class="card-body">

                <div class="row mt-4">
                    <div class="col">
                        <div class="avatar-sm mb-4">
                            <span class="avatar-title rounded-circle bg-soft-dark font-size-18">
                                <i class="fa fa-money-bill text-dark"></i>
                            </span>
                        </div>
                        <p class="mb-0 small">Total Amount</p>
                        <p class="h1 mb-0">${{ object.total }}</p>
                    </div>
                    <div class="col">
                        <div class="avatar-sm mb-4">
                            <span class="avatar-title rounded-circle bg-soft-danger font-size-18">
                                <i class="fa fa-coins text-danger"></i>
                            </span>
                        </div>
                        <p class="mb-0 small text-danger">Tax Charges</p>
                        <p class="h1 mb-0 text-danger">${{ object.tax }}</p>
                    </div>
                    <div class="col">
                        <div class="avatar-sm mb-4">
                            <span class="avatar-title rounded-circle bg-soft-dark font-size-18">
                                <i class="fa fa-hands-helping text-dark"></i>
                            </span>
                        </div>
                        <p class="mb-0 small">Load Received</p>
                        <p class="h1 mb-0">${{ object.received }}</p>
                    </div>
                </div>
            </div>
            <div class="card-body border-top">
                <p class="mb-0"><i class="fa fa-calendar"></i> {{ object.created_on }}</p>
            </div>

        </div>
        <div class="col-4">

            <div class="card">
                <div class="card-body border-bottom">
                    <p class="my-0 card-title">Payment Method</p>
                </div>
                <div class="card-body">

                    <div class="text-center">
                        <h1 class="h1 mb-0">
                            <i class="bx bxl-stripe"></i>
                        </h1>
                        <p class="h3 mb-0">Stripe</p>

                    </div>

                </div>
            </div>

        </div>
    </div>

{% endblock %}

src/portals/admins/templates/admins/topup_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Top Ups {% endblock %}

{% block page_heading %}Top Ups{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-12">

            <div class="card">
                <div class="card-body">
                    {% if object_list %}
                        <div class="table-responsive">
                            <table class="table table-centered table-nowrap table-hover">
                                <thead class="thead-light">
                                <tr>
                                    <th scope="col">Transaction ID</th>
                                    <th scope="col">Amount</th>
                                    <th scope="col">Date</th>
                                    <th scope="col">Payment Method</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for object in object_list %}
                                    <tr>
                                        <td>
                                            <h5 class="text-truncate font-size-14">
                                                <a href="#" class="text-dark">#{{ object.pk }}</a>
                                            </h5>
                                            <p class="text-muted mb-0"></p>
                                        </td>
                                        <td>
                                            <b class=""><i class="fa fa-arrow-up text-success"></i> ${{ object.total }}
                                            </b><br>
                                        </td>
                                        <td>{{ object.created_on }}</td>
                                        <td>
                                    <span class="badge badge-dark">
                                        {{ object.get_payment_method_display }}
                                    </span>
                                        </td>
                                        <td>
                                            {% if object.status == 'com' %}
                                                <b class="text-success"><i
                                                        class="fa fa-check-circle"></i> {{ object.get_status_display }}
                                                </b>
                                            {% elif object.status == 'pen' %}
                                                <b class="text-warning"><i
                                                        class="fa fa-exclamation-triangle"></i>
                                                    {{ object.get_status_display }}
                                                </b>
                                            {% else %}

                                                <b class="text-danger"><i class="fa fa-times-circle"></i>
                                                    {{ object.get_status_display }}
                                                </b>
                                            {% endif %}
                                        <td>
                                            <a href="{% url 'admin-portal:topup-detail' object.pk %}"><b><i
                                                    class="fa fa-eye"></i>
                                                view</b></a>
                                            {% if object.status == 'com' %}
                                                |
                                                <a href="{% url 'admin-portal:topup-invoice' object.pk %}"><b><i
                                                        class="fa fa-print"></i> invoice</b></a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    {% else %}
                        <p class="text-danger">
                            <b><i class="fa fa-exclamation-circle"></i> No Top Ups placed yet.</b>
                        </p>
                    {% endif %}
                </div>
            </div>

        </div>
    </div>

    {% if object_list %}
        <div class="row">
        <div class="col-lg-12">
            <ul class="pagination pagination-rounded justify-content-center mt-4">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1"><<</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <i class="mdi mdi-chevron-left"></i>
                        </a>
                    </li>
                {% endif %}
                <li class="page-item active">
                    <a class="page-link">{{ page_obj.number }}</a>
                </li>
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}"><i
                                class="mdi mdi-chevron-right"></i></a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">>></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
    {% endif %}

{% endblock %}

src/portals/admins/templates/admins/transaction_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Transactions {% endblock %}

{% block page_heading %}Transactions{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-12">

            <div class="card">
                <div class="card-body">
                    {% if object_list %}
                        <div class="table-responsive">
                            <table class="table table-centered table-nowrap table-hover">
                                <thead class="thead-light">
                                <tr>
                                    <th scope="col">Transaction ID</th>
                                    <th scope="col">Sender</th>
                                    <th scope="col">Receiver</th>
                                    <th scope="col">Amount</th>
                                    <th scope="col">Transfer</th>
                                    <th scope="col">Date</th>
                                    <th scope="col">Method</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for object in object_list %}
                                    <tr>
                                        <td>
                                            <h5 class="text-truncate font-size-14"><a href="#"
                                                                                      class="text-dark"># {{ object.pk }}</a>
                                            </h5>
                                            <p class="text-muted mb-0"></p>
                                        </td>
                                        <td>
                                            <div class="row">
                                                <div class="cols pr-4">
                                                        {% if object.sender_wallet.user.profile_image %}
                                                            <img class="rounded-circle avatar-xs"
                                                                 src="{{ object.sender_wallet.user.profile_image.url }}"
                                                                 alt="">
                                                        {% else %}
                                                            <img class="rounded-circle avatar-xs"
                                                                 src="{% static 'core/images/no-user.png' %}" alt="">
                                                        {% endif %}
                                                </div>
                                                <div class="cols">
                                                    <a href="{% url 'admin-portal:user-detail' object.sender_wallet.user.pk %}">
                                                        {% if object.sender_wallet.user.profile_image %}
                                                            <h5 class="text-truncate font-size-14 mb-0">
                                                                {{ object.sender_wallet.user.first_name }}
                                                                {{ object.sender_wallet.user.last_name }}
                                                            </h5>
                                                        {% else %}
                                                            <h5 class="text-truncate font-size-14 mb-0">
                                                                {{ object.sender_wallet.user.username }}
                                                            </h5>
                                                        {% endif %}

                                                        <p class="text-muted mb-0">
                                                            <i class="fa fa-wallet"></i> {{ object.sender_wallet.user.get_user_wallet.pk }}
                                                        </p>
                                                    </a>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="row">
                                                <div class="cols pr-4">
                                                    {% if object.receiver_wallet.user.profile_image %}
                                                        <img class="rounded-circle avatar-xs"
                                                             src="{{ object.receiver_wallet.user.profile_image.url }}"
                                                             alt="">
                                                    {% else %}
                                                        <img class="rounded-circle avatar-xs"
                                                             src="{% static 'core/images/no-user.png' %}" alt="">
                                                    {% endif %}
                                                </div>
                                                <div class="cols">
                                                    <a href="{% url 'admin-portal:user-detail' object.receiver_wallet.user.pk %}">
                                                        {% if object.receiver_wallet.user.first_name %}
                                                            <h5 class="text-truncate font-size-14 mb-0">
                                                                {{ object.receiver_wallet.user.first_name }}
                                                                {{ object.receiver_wallet.user.last_name }}
                                                            </h5>
                                                        {% else %}
                                                            <h5 class="text-truncate font-size-14 mb-0">
                                                                {{ object.receiver_wallet.user.username }}
                                                            </h5>
                                                        {% endif %}

                                                        <p class="text-muted mb-0">
                                                            <i class="fa fa-wallet"></i> {{ object.receiver_wallet.user.get_user_wallet.pk }}
                                                        </p>
                                                    </a>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <b>{{ object.total }}</b>
                                        </td>
                                        <td>{{ object.created_on }}</td>
                                        <td class="text-warning">
                                            <span class="badge badge-dark">{{ object.type }}</span>
                                        </td>
                                        {% if object.status == 'com' %}
                                            <td class="text-success">
                                                <b class=""><i
                                                        class="fa fa-check-circle"></i> {{ object.get_status_display }}
                                                </b>
                                            </td>
                                        {% elif object.status == 'pen' %}
                                            <td class="text-warning"><b class=""><i
                                                    class="fa fa-exclamation-triangle"></i>
                                                {{ object.get_status_display }}
                                            </b></td>
                                        {% else %}
                                            <td class="text-danger">
                                                <b class=""><i class="fa fa-times-circle"></i>
                                                    {{ object.get_status_display }}
                                                </b>
                                            </td>
                                        {% endif %}
                                        <td>
                                            <a href="{% url 'admin-portal:transaction-detail' object.pk %}"><b><i
                                                    class="fa fa-eye"></i> view</b></a>
                                            {% if object.status == 'com' %}
                                                |
                                                <a href="{% url 'admin-portal:transaction-invoice' object.pk %}"><b><i
                                                        class="fa fa-print"></i> invoice</b></a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    {% else %}
                        <p class="text-danger">
                            <b><i class="fa fa-exclamation-circle"></i> No transactions placed yet.</b>
                        </p>
                    {% endif %}
                </div>
            </div>

        </div>
    </div>

    {% if object_list %}
        <div class="row">
        <div class="col-lg-12">
            <ul class="pagination pagination-rounded justify-content-center mt-4">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1"><<</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <i class="mdi mdi-chevron-left"></i>
                        </a>
                    </li>
                {% endif %}
                <li class="page-item active">
                    <a class="page-link">{{ page_obj.number }}</a>
                </li>
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}"><i
                                class="mdi mdi-chevron-right"></i></a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">>></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
    {% endif %}

{% endblock %}