cocognite/urls.py
import notifications.urls
from django.views.generic import TemplateView

from cocognite import settings
from dj_rest_auth.registration.views import VerifyEmailView
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path

from cocognite.settings import ENVIRONMENT
from src.accounts.views import GoogleLoginView, CustomRegisterAccountView
from django.views.static import serve

urlpatterns = [
    path('', include('src.website.urls', namespace='website')),
    path('404/', TemplateView.as_view(template_name='404.html'), name='404'),
    path('500/', TemplateView.as_view(template_name='500.html'), name='500'),
]

urlpatterns += [
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    path('', include('src.payments.urls', namespace='payment-stripe')),
    path('a/', include('src.portals.admins.urls', namespace='admin-portal')),
    path('c/', include('src.portals.customer.urls', namespace='moderator-portal')),
    path('api/', include('src.api.urls', namespace='api')),
    re_path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

urlpatterns += [
    path('auth/', include('dj_rest_auth.urls')),
    path('auth/registration/', CustomRegisterAccountView.as_view(), name='account_create_new_user'),
    path('auth/google/', GoogleLoginView.as_view(), name='google-login-view'),
    # re_path(r'^account-confirm-email/', VerifyEmailView.as_view(), name='account_email_verification_sent'),
    # re_path(r'^account-confirm-email/(?P<key>[-:\w]+)/$', VerifyEmailView.as_view(), name='account_confirm_email'),
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

src/payments/urls.py
from django.urls import path
from .views import (
    stripe_config, create_checkout_session, CancelledView, SuccessView, stripe_webhook,
    ConnectCreateView, ConnectUpdateView, ConnectDetailView, ConnectDeleteView,
    ExternalAccountListView, ExternalAccountUpdateView, ExternalAccountDeleteView, ExternalAccountCreateView,
    )

app_name = 'payment-stripe'

urlpatterns = [
    path('connect/', ConnectDetailView.as_view(), name='connect'),
    path('connect/create/', ConnectCreateView.as_view(), name='connect-create'),
    path('connect/change/', ConnectUpdateView.as_view(), name='connect-update'),
    path('connect/delete/', ConnectDeleteView.as_view(), name='connect-delete'),

    path(
        'connect/external-account/', ExternalAccountListView.as_view(),
        name='connect-external-account'
    ),
    path(
        'connect/external-account/<int:pk>/change/', ExternalAccountUpdateView.as_view(),
        name='connect-external-account-change'
    ),
    path(
        'connect/external-account/create/', ExternalAccountCreateView.as_view(),
        name='connect-external-account-create'
    ),
    path(
        'connect/external-account/<int:pk>/delete/', ExternalAccountDeleteView.as_view(),
        name='connect-external-account-delete'
    ),

]

urlpatterns += [
    path('config/', stripe_config, name='stripe-config'),
    path('create-checkout-session/<int:pk>/', create_checkout_session, name='stripe-balance-load'),  # new
    path('success/', SuccessView.as_view(), name='success'),  # new
    path('cancelled/', CancelledView.as_view(), name='cancel'),  # new
    path('webhook/', stripe_webhook, name='stripe-webhook'),
]

src/portals/customer/urls.py
from django.urls import path
from .views import (
    DashboardView, WalletDetailView, WalletGenerateQRCodeView,
    TopUpListView, TopUpInvoiceView, TopUpDetailView, TopUpCreateView,
    TransactionListView, TransactionDetailView, TransactionInvoiceView, TransactionCreateView,
    WithdrawalListView, WithdrawalInvoiceView, WithdrawalDetailView, WithdrawalCreateView,
    UserSanctionsUpdateView,
    TicketListView, TicketCreateView, TicketDetailView,
    TransferFunds)

app_name = "customer-portal"
urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('wallet/', WalletDetailView.as_view(), name='wallet-detail'),
    path('wallet/<int:pk>/generate/qr-code/', WalletGenerateQRCodeView.as_view(), name='generate-qr-code'),
    path('user/sanctions/change/', UserSanctionsUpdateView.as_view(), name='user-sanctions-change'),

    path('topup/', TopUpListView.as_view(), name='topup-list'),
    path('topup/add/', TopUpCreateView.as_view(), name='topup-create'),
    path('topup/<int:pk>/', TopUpDetailView.as_view(), name='topup-detail'),
    path('topup/<int:pk>/invoice/', TopUpInvoiceView.as_view(), name='topup-invoice'),

    path('transaction/', TransactionListView.as_view(), name='transaction-list'),
    path('transaction/add/', TransactionCreateView.as_view(), name='transaction-create'),
    path('transaction/<int:pk>/', TransactionDetailView.as_view(), name='transaction-detail'),
    path('transaction/<int:pk>/invoice/', TransactionInvoiceView.as_view(), name='transaction-invoice'),

    path('withdrawal/', WithdrawalListView.as_view(), name='withdrawal-list'),
    path('withdrawal/add/', WithdrawalCreateView.as_view(), name='withdrawal-create'),
    path('withdrawal/<int:pk>/', WithdrawalDetailView.as_view(), name='withdrawal-detail'),
    path('withdrawal/<int:pk>/invoice/', WithdrawalInvoiceView.as_view(), name='withdrawal-invoice'),

    path('ticket/', TicketListView.as_view(), name='ticket-list'),
    path('ticket/add/', TicketCreateView.as_view(), name='ticket-create'),
    path('ticket/<int:pk>/', TicketDetailView.as_view(), name='ticket-detail'),

    path('transfers/', TransferFunds.as_view(), name='transfer')
]

src/payments/models.py
from django.db import models
from django_resized import ResizedImageField

STRIPE_ACCOUNT_TYPE_CHOICES = (
    ('s', "Standard"),
    ('e', "Express"),
    ('c', "Custom"),
)

STRIPE_BUSINESS_TYPE_CHOICES = (
    ('i', "Individual"),
    ('c', "Company"),
    ('n', "Non-Profit"),
    ('g', "Government Entity"),
)

STRIPE_PAYMENT_TYPE_CHOICES = (
    ('w', "Wallet"),
    ('c', "Card"),
    ('b', "Bank Account"),
)


class StripeAcceptedCountry(models.Model):
    country = models.ForeignKey('admins.Country', on_delete=models.CASCADE)

    def __str__(self):
        return self.country.name

    class Meta:
        ordering = ['-id']
        verbose_name_plural = "Stripe Accepted Countries"


class City(models.Model):
    name = models.CharField(max_length=255)
    country = models.ForeignKey('admins.Country', on_delete=models.SET_NULL, null=True, blank=False)

    class Meta:
        ordering = ['-id']
        verbose_name_plural = 'Cities'

    def __str__(self):
        return self.name


class Currency(models.Model):
    name = models.CharField(max_length=255, unique=True)
    short_code = models.CharField(max_length=3, unique=True)
    symbol = models.CharField(default='dollar', max_length=100)

    class Meta:
        ordering = ['-id']
        verbose_name_plural = 'Currencies'

    def __str__(self):
        return self.name


from phonenumber_field.modelfields import PhoneNumberField


class Connect(models.Model):
    BUSINESS_TYPE_CHOICE = (
        ('individual', 'individual'),
    )
    connect_id = models.CharField(max_length=1000, null=True, blank=True, editable=False)
    user = models.OneToOneField('accounts.User', on_delete=models.CASCADE, blank=True)
    first_name = models.CharField(max_length=255, help_text="First Name for user", blank=True)
    last_name = models.CharField(max_length=255, help_text="Last Name for user", blank=True)
    email = models.EmailField(help_text="Your professional email that will be linked with connect account", blank=True)
    phone = PhoneNumberField(help_text="Phone number that will be linked with connect account")

    country = models.ForeignKey(
        StripeAcceptedCountry, on_delete=models.SET_NULL, null=True, blank=False,
        help_text="Select the country in which you reside now, according to your according payments methods, wallets "
                  "and bank accounts will be visible"
    )
    city = models.ForeignKey(City, on_delete=models.SET_NULL, help_text="Select your city", null=True, blank=True)
    currency = models.ForeignKey(Currency, null=True, blank=False, on_delete=models.SET_NULL)

    postal_code = models.CharField(
        max_length=255, null=True, blank=True, help_text="Postal code according to your country and city"
    )
    address = models.CharField(max_length=1000, null=True, blank=True, help_text="Your home or office address.")
    description = models.CharField(max_length=5000, null=True, blank=True)
    business_type = models.CharField(max_length=255, choices=BUSINESS_TYPE_CHOICE, default='individual')

    is_active = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Stripe Customer'

    def __str__(self):
        return self.user.username

    def get_external_accounts(self):
        return self.externalaccount_set.all()

    def get_external_accounts_verified(self):
        return self.externalaccount_set.filter(is_verified=True)


class ExternalAccount(models.Model):
    BUSINESS_TYPE_CHOICE = (
        ('individual', 'individual'),
    )
    ACCOUNT_TYPE_CHOICE = (
        ('card', 'Card'),
        ('bank', 'Bank'),
    )
    external_account_id = models.CharField(max_length=1000, null=True, blank=True)
    connect = models.ForeignKey(Connect, on_delete=models.CASCADE)
    country = models.ForeignKey(
        StripeAcceptedCountry, on_delete=models.SET_NULL, blank=False, null=True,
        help_text="Select Bank/Card Country Name"
    )
    currency = models.ForeignKey(
        Currency, blank=False, null=True, on_delete=models.SET_NULL,
        help_text="Select Currency according to your account"
    )
    account_holder_name = models.CharField(
        max_length=255, blank=False, help_text="Your full name on card or bank account"
    )
    account_holder_type = models.CharField(
        max_length=255, choices=BUSINESS_TYPE_CHOICE, default='individual',
    )
    account_type = models.CharField(
        max_length=255, choices=ACCOUNT_TYPE_CHOICE, default='bank',
    )
    routing_number = models.CharField(
        verbose_name='RoutingNumber/SortCode', max_length=255, blank=False,
        help_text="Use '108800' for testing purpose -- SortCode for UK and Routing Number for US customers"
    )
    account_number = models.CharField(max_length=255, blank=False, help_text="Use '00012345' for testing purpose")

    created_on = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_verified = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'External Account'

    def __str__(self):
        return str(self.connect.connect_id)

src/portals/admins/models.py
from django.db import models
from django_resized import ResizedImageField
from src.accounts.models import Wallet


""" GENERAL """


class Country(models.Model):

    name = models.CharField(max_length=255, unique=True)
    short_code = models.CharField(max_length=2, unique=True)
    phone_code = models.CharField(max_length=5, unique=True)
    description = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Countries'

    def __str__(self):
        return self.name


""" MAIN """


class PaymentMethod(models.Model):
    name = models.CharField(max_length=255)
    icon = models.CharField(max_length=100, default="bx bx-transfer")
    image = ResizedImageField(
        upload_to='accounts/images/profiles/', null=True, blank=True, size=[100, 100], quality=75, force_format='PNG',
        help_text='size of image must be 100*100 and format must be png image file', crop=['middle', 'center']
    )
    description = models.TextField(null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = "Payment Methods"

    def __str__(self):
        return self.name


class TopUp(models.Model):
    STATUS_CHOICE = (
        ('com', 'Completed'),
        ('pen', 'Pending'),
        ('can', 'Cancelled'),
    )
    PAYMENT_METHOD_CHOICE = (
        ('str', 'Stripe'),
    )

    total = models.PositiveIntegerField()
    tax = models.PositiveIntegerField()
    received = models.PositiveIntegerField()
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE, blank=True)
    stripe_payment_intent = models.CharField(max_length=20000)
    status = models.CharField(choices=STATUS_CHOICE, max_length=3, default='pen')
    payment_method = models.CharField(choices=PAYMENT_METHOD_CHOICE, max_length=3, default='str')

    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']
        verbose_name_plural = "Top Ups"

    def __str__(self):
        return str(self.pk)


class Withdrawal(models.Model):
    STATUS_CHOICE = (
        ('com', 'Completed'),
        ('pen', 'Pending'),
        ('can', 'Cancelled'),
    )

    total = models.FloatField(verbose_name='Amount')
    tax = models.FloatField(default=0)
    received = models.FloatField(default=0)
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE, blank=True)
    connected_account = models.ForeignKey(
        'payments.ExternalAccount', on_delete=models.SET_NULL, null=True, blank=True
    )
    status = models.CharField(choices=STATUS_CHOICE, max_length=3)

    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']
        verbose_name_plural = "Withdrawals"

    def __str__(self):
        return str(self.pk)


class Transaction(models.Model):
    STATUS_CHOICE = (
        ('com', 'Completed'),
        ('pen', 'Pending'),
        ('can', 'Cancelled'),
    )
    TYPE_CHOICE = (
        ('p2p', 'Peer To Peer'),
    )

    total = models.PositiveIntegerField(default=0)
    tax = models.PositiveIntegerField(default=0)
    received = models.PositiveIntegerField(default=0)
    sender_wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE, blank=True, related_name='sender+')
    receiver_wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE, blank=True, related_name='receiver+')
    type = models.CharField(choices=TYPE_CHOICE, max_length=3, default='p2p')
    status = models.CharField(choices=STATUS_CHOICE, max_length=3, default='pen')

    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']
        verbose_name_plural = "Transactions"

    def __str__(self):
        return str(self.pk)


""" TICKET SYSTEM """


class TicketType(models.Model):
    PRIORITY_CHOICES = (
        ('h', 'High'),
        ('m', 'Medium'),
        ('l', 'Low'),
    )
    name = models.CharField(max_length=255)
    priority = models.CharField(max_length=1, choices=PRIORITY_CHOICES, default='m')

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.name


class Ticket(models.Model):
    PRIORITY_CHOICES = (
        ('h', 'High'),
        ('m', 'Medium'),
        ('l', 'Low'),
    )
    ticket_type = models.ForeignKey(TicketType, on_delete=models.CASCADE)
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)

    is_completed = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return str(self.pk)

src/payments/forms.py
from django.forms import ModelForm
from src.payments.models import Connect, ExternalAccount


class ConnectCreateForm(ModelForm):
    class Meta:
        model = Connect
        fields = [
            'first_name', 'last_name', 'phone', 'country', 'city', 'currency', 'postal_code', 'address'
        ]


class ConnectUpdateForm(ModelForm):
    class Meta:
        model = Connect
        fields = [
            'first_name', 'last_name', 'email', 'phone', 'city', 'postal_code', 'address'
        ]


class ExternalAccountCreateForm(ModelForm):
    class Meta:
        model = ExternalAccount
        fields = [
            'country', 'currency', 'account_holder_name', 'routing_number', 'account_number'
        ]


class ExternalAccountUpdateForm(ModelForm):
    class Meta:
        model = ExternalAccount
        fields = [
            'country', 'currency', 'account_holder_name', 'routing_number', 'account_number'
        ]

src/payments/templates/payments/cancelled.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %}
    Success
{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-6">

            <div class="card">
                <div class="card-body border-bottom text-center">
                    <img src="{% static 'core/images/SKISIP WALLET.png' %}" height="200">
                </div>
                <div class="card-body">
                    <p class="card-title">Payment Failed</p>
                    <p>
                        Payment failed, retry again please - For more help contact with us<br>
                        <a href="mailto:"><b>support@rsonlineaccounting.com</b></a>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/payments/templates/payments/connect_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Connect {% endblock %}

{% block page_heading %}
    <b><i class="fa fa-link"></i>
        {% if object.connect_id %}
            {{ object.connect_id }}
        {% else %}
            <a href="{% url 'payment-stripe:connect-verify' %}">Verify your account</a>
        {% endif %}

    </b>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-sm-8">

            <div class="card">
                <div class="card-body">

                    <div class="media">


                        <div class="media-body">
                            <div class="text-muted">
                                <h5>

                                    {{ object.first_name }} {{ object.last_name }}

                                </h5>
                                <p class="mb-1">{{ object.email }}</p>
                                <p class="mb-0">{{ object.phone }}</p>
                                <p class="mb-0">{{ object.address }}</p>
                                <p class="mb-0">{{ object.city }} <b>({{ object.postal_code }})</b>
                                    - {{ object.country }}</p>
                            </div>

                        </div>

                        <div class="dropdown ml-2">
                            <a class="text-muted dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                <i class="mdi mdi-dots-horizontal font-size-18"></i>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" style="">
                                <a class="dropdown-item" href="#">View</a>
                                <a class="dropdown-item" href="#">Edit</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body border-top">

                    <div class="row">
                        <div class="col-sm-6">
                            <div>
                                <p class="text-muted mb-2">Available Balance</p>
                                <h5>&{{ object.currency.symbol }}; {{ request.user.get_user_wallet.connect_amount }}</h5>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="text-sm-right mt-4 mt-sm-0">
                                <p class="text-muted mb-2">Connect Account Permissions</p>
                                <p>
                                    <b class="p-1 bg-success text-white mr-2">
                                        Transfers: Yes
                                    </b>
                                    <b class="p-1 bg-success text-white">
                                        Payouts: Yes
                                    </b>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="card">
                <div class="card-body border-bottom">
                    <p class="mb-0 card-title">Payment Methods</p>
                </div>
                <div class="card-body">
                    {% if object.get_external_accounts %}
                        <div class="table-responsive">
                            <table class="table table-striped table-borderless table-hover">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Currency</th>
                                    <th>Routing Number</th>
                                    <th>Account Number</th>
                                    <th>Status</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>

                                {% for acc in object.get_external_accounts %}
                                    <tr>
                                        <th>
                                            {% if acc.is_verified %}
                                                {{ acc.external_account_id }}
                                            {% else %}
                                                -
                                            {% endif %}

                                        </th>
                                        <th><b class="mb-0">{{ acc.currency.short_code }}</b></th>
                                        <th><b class="mb-0">{{ acc.routing_number }}</b></th>
                                        <th><b class="mb-0">{{ acc.account_number }}</b></th>
                                        <th>
                                            {% if acc.is_verified %}
                                                <b class="mb-0"><a href="#" class="text-success">
                                                    <i class="fa fa-check-circle"></i> verified</a>
                                                </b>
                                            {% else %}
                                                <b class="mb-0">
                                                    <i class="fa fa-times-circle"></i> Not verified
                                                </b>
                                            {% endif %}
                                        </th>
                                        <th>
                                            <b class="mb-0">
                                                <a href="{% url 'payment-stripe:connect-external-account-change' acc.pk %}"
                                                   class="text-primary">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                            </b>
                                            <b class="mb-0">
                                                <a href="{% url 'payment-stripe:connect-external-account-delete' acc.pk %}"
                                                   class="text-danger">
                                                    <i class="fa fa-trash"></i>
                                                </a>

                                            </b>
                                        </th>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    {% else %}
                        <p class="text-danger"><b>No external bank/card account attached yet.</b></p>
                    {% endif %}

                    <p class="text-danger mb-0">
                        <a href="{% url 'payment-stripe:connect-external-account-create' %}">
                            <b>Attach new bank/card here.</b>
                        </a>
                    </p>
                </div>
            </div>

        </div>
        <div class="col-sm-4">

            {# DELETE #}
            <div class="card">
                <div class="card-body border-bottom">
                    <p class="mb-0 card-title">Remove Account</p>
                </div>
                <div class="card-body">
                    <p class="card-text">
                        <b>
                            To update you are only allowed to update basic information whereas to delete your connect account,
                            there is no way to get back your data related to this account.
                        </b>
                    </p>
                    <a href="{% url 'payment-stripe:connect-update' %}" class="btn btn-primary">Update
                        Account
                    </a>
                    <a href="{% url 'payment-stripe:connect-delete' %}" class="btn btn-danger">Delete
                        Account
                    </a>
                </div>
            </div>

            {# TRANSFER #}
            <div class="card">
                <div class="card-body border-bottom">
                    <p class="mb-0 card-title">Transfer Funds</p>
                </div>
                <div class="card-body">
                    <p class="card-text mb-0">
                            To transfer funds from your wallet to connect account for withdrawals.
                    </p>
                    <a href="{% url 'customer-portal:transfer' %}" class="">
                        <b>Click Here to transfer funds</b>
                    </a>
                </div>
            </div>

        </div>
    </div>

{% endblock %}

src/payments/templates/payments/externalaccount_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} External Account {% endblock %}
{% block content %}

    <div class="row mb-2">
        <div class="col-12">

            <a class="btn btn-primary" href="{% url 'payment-stripe:connect-external-account-create' %}">
                <i class="fa fa-arrow-up"></i> Attach Bank/Card
            </a>

        </div>
    </div>

    <div class="row">
        <div class="col-12">

            {% if object_list %}
                <div class="row">

                    {% for object in object_list %}
                        <div class="col-sm-3">

                            <div class="card">
                                <div class="card-body text-center border-bottom">

                                    <p class="h1 mb-0">
                                        <img alt="bank-pic"
                                             src="{% static 'core/portals/images/icons8-mastercard-100.png' %}">
                                    </p>
                                    <p class="mb-0"><b>{{ object.account_type }} Account</b></p>
                                    {% if object.is_verified %}

                                        <p class="mb-0 text-muted">
                                            <b>
                                                ( <i class="fa fa-check-circle text-success"></i> verified )
                                            </b>
                                        </p>

                                    {% else %}

                                        <p class="mb-0 text-muted">
                                            <b>
                                                ( <i class="fa fa-times-circle text-danger"></i>
                                                non-verified,
                                                <a href="{% url 'payment-stripe:connect-external-account-verify' object.pk %}">Verify here</a>
                                                )
                                            </b>
                                        </p>

                                    {% endif %}

                                </div>
                                <div class="card-body text-center">
                                    <p class="mb-0"><a href="#"><b>{{ object.account_holder_name }}</b></a></p>
                                    <p class="mb-0"><a href="#"><b>{{ object.account_number }}</b></a></p>
                                    <p class=""><a href="#"><b>{{ object.country }} ({{ object.currency.short_code }})</b></a></p>
                                    <p class="mb-0 text-muted">{{ object.created_on }}</p>
                                </div>
                                <div class="border-top card-body">
                                    <div class="row text-center">
                                        <div class="col">
                                            <b><a href="{% url 'payment-stripe:connect-external-account-change' object.pk %}"><i class="fa fa-eye"></i></a></b>
                                        </div>
                                        <div class="col">
                                            <b><a href="{% url 'payment-stripe:connect-external-account-change' object.pk %}"><i class="fa fa-edit"></i></a></b>
                                        </div>
                                        <div class="col">
                                            <b><a href="{% url 'payment-stripe:connect-external-account-delete' object.pk %}" class="text-danger"><i class="fa fa-trash"></i></a></b>
                                        </div>
                                    </div>
                                </div>
                            </div>


                        </div>
                    {% endfor %}

                </div>
            {% else %}
                <p class="mb-0 text-danger"><b>No external accounts are created yet.</b></p>
            {% endif %}

        </div>
    </div>


{% endblock %}